[package]
name = "rvsim-cpu"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
rvsim-isa = { path = "../isa" }
rvsim-system = { path = "../system" }

[dev-dependencies]
rvsim-devices = { path = "../devices" }

[lib]
name = "rvsim_cpu"
path = "src/lib.rs"
