[package]
name = "rvsim-computer"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
rvsim-cpu = { path = "../../crates/cpu" }
rvsim-devices = { path = "../../crates/devices" }
rvsim-isa = { path = "../../crates/isa" }
rvsim-system = { path = "../../crates/system" }

[[bin]]
name = "computer"
path = "src/main.rs"

[[bin]]
name = "memory_microbench"
path = "src/bin/memory_microbench.rs"
